import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";


export const metadata: Metadata = { /*SEO metadata refers to snippets of text and HTML code that describe a page's content, allowing search engines to understand and display it properly */
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, /*represents whatever page is currently being rendered */
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );  
}
